version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - <postgres_data>:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: fastapi_container
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      # DATABASE_URL: postgresql+asyncpg://user:password@db:5432/mydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres 
      - POSTGRES_HOST=db             
      - POSTGRES_PORT=5432
      - POSTGRES_DB=mydb
      - PYTHONUNBUFFERED=1           
    volumes:
      - .:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--log-level", "debug"]

volumes:
  postgres_data: